- name:
  hosts: all
  collections:
  - fortinet.fortiadc
  connection: httpapi
  gather_facts: false
  tasks:
        - name: Create basic virtual server
          fadcos_virtual_server_basic:
           name: test
           application: http
           address: 7.7.7.7
           interface: port3
           pool: rs_pool
           port: 80
