- name: Manage FortiADC real servers
  hosts: fortiadcs
  collections:
    - fortinet.fortiadc
  connection: httpapi
  gather_facts: false
  vars_files:
    - /tmp/vault.yml  # Load encrypted variables
         
  tasks:
    - name: Create/Verify real server and change status to 'disable'
      fadcos_real_server:
        action: add
        name: "{{ item.name }}"
        ip: "{{ item.ip }}"
        status: disable
        vdom: root
      loop: "{{ real_servers }}"
                    
    - name: Update IP addresses of real servers
      fadcos_real_server:
        action: edit
        name: "{{ item.name }}"
        ip: "{{ item.ip }}"
        status: "{{ item.status }}"
        vdom: root
      loop: "{{ real_servers }}"
      
    - name: Manage Health Checks LBHC_HTTP_200
      fadcos_health_check:
        action: add
        name: LBHC_HTTP_200
        status_code: 200
        send_string: /
        dest_addr_type: ipv4
        hc_type: http
      no_log: true  
                    
    - name: Manage Real Server Pool $x{{ pool_name }}
      fadcos_real_server_pool:
        action: add
        name: "{{ pool_name }}"
        iptype: "{{ iptype }}"
        vdom: "{{ vdom }}"
        healthcheck: enable
        health_check_list:
          - LBHC_HTTP_200
            
    - name: Manage real server pool member 
      fadcos_real_server_pool_member:
        action: add
        pool_name: "{{ pool_name }}"
        status: "{{ item.status }}"
        member_id: "{{ item.id }}"
        port: "{{ item.port }}"
        rs: "{{ item.name }}"
        weight: "{{ item.weight }}"
      loop: "{{ real_servers }}"
            
    - name: Create basic virtual server {{ virtual_server_name }}
      fadcos_virtual_server:
        name: "{{ virtual_server_name }}"
        status: enable
        action: add
        iptype: ipv4
        ip: "{{ virtual_server_ip }}"
        pool: "{{ pool_name }}"
        port: "{{ virtual_server_port }}"
        interface: "{{ virtual_server_interface }}"
        profile: LB_PROF_HTTP
        vstype: l7-load-balance
