apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:
    app.kubernetes.io/part-of: newsletter-subscription
    apps.tanzu.vmware.com/carvel-package-workflow: "true"
    apps.tanzu.vmware.com/has-tests: "false"
    apps.tanzu.vmware.com/workload-type: web
  name: newsletter-subscription
  namespace: newsletter
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: "20"
  source:
    git:
      ref:
        branch: main
      url: https://github.com/sdubois-tapdemo/newsletter
    subPath: newsletter-subscription
