apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tanzu-demo-hub
spec:
  secretName: tanzu-demo-hub-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - '*.apps-contour.vsptap.pcfsdu.com'
  - '*.apps-nginx.vsptap.pcfsdu.com'
  - '*.gitlab.vsptap.pcfsdu.com'
  - '*.cnrs.vsptap.pcfsdu.com'
  - 'learningcenter.vsptap.pcfsdu.com'
  - 'tap-gui.vsptap.pcfsdu.com'
