apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: sdubois@vmware.com
    privateKeySecretRef:
      name: letsencrypt-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - selector:
        dnsZones:
          - "*.apps-contour.vsptap.pcfsdu.com"
          - "*.apps-nginx.vsptap.pcfsdu.com"
          - "*.gitlab.vsptap.pcfsdu.com"
          - "*.cnrs.vsptap.pcfsdu.com"
          - "learningcenter.vsptap.pcfsdu.com"
          - "tap-gui.vsptap.pcfsdu.com"
      dns01:
        route53:
          region: eu-central-1
          accessKeyID: AKIAWRX6KKSGEJPP6MXX
          secretAccessKeySecretRef:
            name: route53-credentials-secret
            key: aws-credentials
          hostedZoneID: Z00457083JMUT2MEP6AV3
