apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster-1
  namespace: tanzu-demo-hub
spec:
  distribution:
    fullVersion: v1.22.9---vmware.1-tkg.1.cc71bc8
    version: 
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
        - 172.20.0.0/16
      serviceDomain: cluster.local
      services:
        cidrBlocks:
        - 10.96.0.0/16
    storage: 
      defaultClass: vc01cl01-t0compute
  topology:
    controlPlane:
      class: best-effort-large
      count: 1
      storageClass: vc01cl01-t0compute
    workers:
      #class: best-effort-2xlarge
      class: best-effort-large
      count: 1
      storageClass: vc01cl01-t0compute
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 200Gi

