apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster-1
  namespace: tanzu-demo-hub
spec:
  distribution:
    fullVersion: v1.20.9+vmware.1-tkg.1.a4cee5b
    version: ""
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks:
        - 172.20.0.0/16
      serviceDomain: cluster.local
      services:
        cidrBlocks:
        - 10.96.0.0/16
    storage: 
      defaultClass: VSPHERE_TKGS_SUPERVISOR_STORAGE_CLASS
  topology:
    controlPlane:
      class: guaranteed-medium
      count: 1
      storageClass: VSPHERE_TKGS_SUPERVISOR_STORAGE_CLASS
    workers:
      #class: best-effort-2xlarge
      class: guaranteed-medium
      count: 1
      storageClass: VSPHERE_TKGS_SUPERVISOR_STORAGE_CLASS
