- name: Manage FortiADC real servers
  hosts: fortiadcs
  collections:
    - fortinet.fortiadc
  connection: httpapi
  gather_facts: false
  vars_files:
    - /tmp/vault.yml  # Load encrypted variables
         
  tasks:
    - name: Add real servers
      fadcos_real_server:
        action: add
        name: "{{ item.name }}"
        ip: "{{ item.ip }}"
        status: disable
        vdom: root
      loop: "{{ real_servers }}"
                    
